/**
 * Self-check for the dsh-sandbox-allowlist package.
 *
 * Run inside the dsh installation context so `@deepseek-ai/*` resolves to the
 * installed packages. On this machine:
 *
 *   node --experimental-loader ./.dsh-test-resolve-hook.mjs test.mjs
 *
 * (the resolve-hook is generated by the dsh tooling; see README "验证").
 * Without the hook the @deepseek-ai imports fail to resolve — the pattern
 * checks can still be run standalone by commenting the plugin imports.
 */

import assert from 'node:assert/strict'
import { createHash } from 'node:crypto'
import { existsSync, mkdtempSync, mkdirSync, readdirSync, readFileSync, realpathSync, statSync, writeFileSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

import {
  hasMeta,
  patternToRegExp,
  expandTrustedRoots,
} from '../lib/patterns.mjs'
import {
  normalizeCommand,
  patternToCommandRegExp,
  compileCommandRules,
  validateCommandRule,
} from '../lib/command-rules.mjs'
import {
  decideCommand,
  dispositionForAction,
  denyReason,
} from '../lib/command-gate.mjs'
import {
  describeStatement,
} from '../lib/command-rules.mjs'
import { decide, makeScopePredicate } from '../lib/command-decision.mjs'
import { classifyStatement, capabilityTables } from '../lib/command-classes.mjs'
import { analyzeCommand } from '../lib/command-analyze.mjs'
import { makeScriptExpander, scriptNameOf } from '../lib/command-expand.mjs'
import {
  CommandAudit,
  ProposalStore,
  describeProposal,
  explainDecision,
} from '../lib/command-audit.mjs'
import {
  NO_READ_ACTIONS,
  NO_READ_TOOLS,
  validateNoReadRule,
  compileNoReadRules,
  noReadRuleIssues,
  resolveNoRead,
} from '../lib/read-deny.mjs'
import {
  stripDaclSddl,
  revokeWriteAces,
  collectRevokeDirs,
  resolvePowerShell,
} from '../lib/acl-revoke.mjs'
import {
  writeSidForDirectory,
  parseDaclHits,
} from '../lib/acl-scan.mjs'
import {
  MANIFEST_FILE_NAME,
  MANIFEST_VERSION,
  HISTORY_LIMIT,
  manifestPath,
  loadManifest,
  saveManifest,
  emptyWorkspaceRecord,
  emptyRootEntry,
  workspaceRecord,
  rootEntryAt,
  ensureRootEntry,
  removeRootEntry,
  activeEntries,
  isExcludedPath,
  diffGrantedV2,
  refreshFromPatterns,
  pushHistory,
  moveRootToHistory,
  enterPendingRevoke,
  dropPendingRevoke,
} from '../lib/grant-manifest.mjs'
import AllowlistPolicyService, { SETTINGS_ENTRY_ID, AllowlistSettingsSchema, CommandRuleSchema, CommandSettingsSchema } from '../lib/policy.mjs'
import AllowlistFileSystem from '../lib/fs.mjs'
import providerDefault, { AllowlistSandboxProvider } from '../lib/provider.mjs'
import { SandboxPolicyService } from '@deepseek-ai/dsh-sandbox-policy'
import { SandboxedFileSystem } from '@deepseek-ai/dsh-fs-sandbox'
import { LocalSandboxProvider } from '@deepseek-ai/dsh-sandbox-local'

// ── pattern matcher ────────────────────────────────────────────────────────
assert.equal(hasMeta('D:\\Shared\\Tools'), false)
assert.equal(hasMeta('D:\\Data\\logs\\*'), true)
assert.equal(hasMeta('D:\\**\\cache'), true)

const reDoubleStar = patternToRegExp('D:\\Shared\\**')
assert.ok(reDoubleStar.test('D:\\Shared\\a'))
assert.ok(reDoubleStar.test('D:\\Shared\\a\\b\\c'))
assert.ok(!reDoubleStar.test('D:\\SharedOther\\a'))

const reSingleStar = patternToRegExp('D:\\Data\\logs\\*')
assert.ok(reSingleStar.test('D:\\Data\\logs\\x'))
assert.ok(!reSingleStar.test('D:\\Data\\logs\\x\\y'))

// ── command rules ──────────────────────────────────────────────────────────
// normalizing collapses surrounding and inner whitespace; ignores casing on win32
assert.equal(normalizeCommand('  git   status  '), 'git status')
assert.equal(normalizeCommand(''), '')
assert.equal(normalizeCommand(null), '')

// wildcard translation: `*` any run, `?` one char, anchored
const gitAny = patternToCommandRegExp('git *')
assert.ok(gitAny.test('git status --porcelain'))
assert.ok(gitAny.test('git commit -m hi'))
assert.ok(!gitAny.test('git'))
const gitCommit = patternToCommandRegExp('git commit *')
assert.ok(gitCommit.test('git commit -m hi'))
assert.ok(!gitCommit.test('git status'))
assert.ok(patternToCommandRegExp('git statu?').test('git status'))

// last-match-wins with tool-aware rules
const rules = [
  { tool: 'bash', pattern: 'git *', action: 'allow' },
  { tool: 'pwsh', pattern: 'git *', action: 'ask' },
  { pattern: 'rm -rf *', action: 'deny' }, // tool omitted ⇒ all tools
  { tool: 'bash', pattern: 'git push *', action: 'deny' }, // more specific, later
]
const match = compileCommandRules(rules)
assert.equal(match('bash', 'git status'), 'allow')
assert.equal(match('pwsh', 'git status'), 'ask')
assert.equal(match('bash', 'git push origin main'), 'deny') // last match wins
assert.equal(match('bash', 'rm -rf /tmp/x'), 'deny')        // tool-omitted applies to bash
assert.equal(match('pwsh', 'rm -rf /tmp/x'), 'deny')        // and to pwsh
assert.equal(match('bash', 'npm test'), null)               // no match

// resolveCommandAction was removed: the gates call compileCommandRules and
// apply the configured fallback themselves (null ⇒ delegate/ask/deny default,
// asserted by the `npm test` line above)

// malformed rules are skipped, never thrown
assert.equal(validateCommandRule({ pattern: 'git *', action: 'allow' }), null)
assert.ok(validateCommandRule({ pattern: 'git *', action: 'bogus' }) !== null)
assert.ok(validateCommandRule({ pattern: '' }) !== null)
assert.ok(validateCommandRule({ tool: 'cmd', pattern: 'x', action: 'allow' }) !== null)
assert.ok(validateCommandRule({ pattern: 'git *', action: 'allow-escalate' }) !== null, 'allow-escalate was removed: it is no longer a valid action')
assert.ok(validateCommandRule({ program: 'git', action: 'allow' }) !== null, 'the argv-level program selector was removed')

// gate decision → PreToolDecision-shaped result, with delegate sentinel
assert.equal(decideCommand({ rules, default: 'delegate' }, 'bash', 'npm test'), 'delegate')
assert.deepEqual(decideCommand({ rules }, 'bash', 'git status'), { kind: 'allow' })
assert.deepEqual(decideCommand({ rules }, 'bash', 'git push origin main'), { kind: 'deny' })
assert.deepEqual(decideCommand({ rules, default: 'ask' }, 'bash', 'npm test'), { kind: 'ask' })
assert.deepEqual(decideCommand({ rules }, 'bash', 'GIT STATUS'), { kind: 'allow' }) // win32 case-insensitive
assert.equal(dispositionForAction('allow').kind, 'allow')
assert.equal(dispositionForAction('deny').kind, 'deny')
assert.equal(dispositionForAction('ask').kind, 'ask')
assert.equal(dispositionForAction('bogus'), 'delegate')
assert.match(denyReason('bash', 'rm -rf /'), /deny rule/)

// command rule / settings schemas validate and reject junk
{
  const ruleResult = CommandRuleSchema['~standard'].validate({ pattern: 'git *', action: 'allow' })
  assert.ok('value' in ruleResult, 'command rule validates: ' + JSON.stringify(ruleResult.issues))
  assert.equal(ruleResult.value.pattern, 'git *')
  const toolResult = CommandRuleSchema['~standard'].validate({ tool: 'bash', pattern: 'git *', action: 'allow' })
  assert.ok('value' in toolResult, 'rule with tool validates')
  const badAction = CommandRuleSchema['~standard'].validate({ pattern: 'git *', action: 'go' })
  assert.ok('issues' in badAction, 'rule rejects an unknown action')
  const badTool = CommandRuleSchema['~standard'].validate({ tool: 'cmd', pattern: 'x', action: 'allow' })
  assert.ok('issues' in badTool, 'rule rejects an unknown tool')

  const cmds = CommandSettingsSchema['~standard'].validate({ default: 'ask', rules: [{ pattern: 'git *', action: 'allow' }] })
  assert.ok('value' in cmds, 'commands settings validates')
  assert.equal(cmds.value.default, 'ask')
  assert.equal(cmds.value.rules.length, 1)
}

// ── ACL reclamation (SDDL strip is pure; spawn helpers stay platform-safe) ──
  {
    // explicit + inherited copies of the workspace SID are dropped in one pass
    const sddl = 'D:AI(A;OICI;0x110156;;;S-1-4-1-2)(A;OICIID;0x110156;;;S-1-4-1-2)(A;ID;FA;;;BA)'
    const out = stripDaclSddl(sddl, 'S-1-4-1-2')
    assert.equal(out.count, 2)
    assert.equal(out.sddl, 'D:AI(A;ID;FA;;;BA)')

    // absent SID → untouched, zero count
    const untouched = stripDaclSddl('D:(A;ID;FA;;;SY)', 'S-1-4-9-9')
    assert.equal(untouched.count, 0)
    assert.equal(untouched.sddl, 'D:(A;ID;FA;;;SY)')

    // every segment naming the SID is removed, others preserved in order
    const multiple = stripDaclSddl('D:(A;OICI;0x110156;;;S-1-4-7-8)(A;ID;0x1301bf;;;AU)(A;OICI;0x110156;;;S-1-4-7-8)', 'S-1-4-7-8')
    assert.equal(multiple.count, 2)
    assert.equal(multiple.sddl, 'D:(A;ID;0x1301bf;;;AU)')

    // an empty/short DACL round-trips unchanged
    assert.equal(stripDaclSddl('D:', 'S-1-4-1-1').sddl, 'D:')

    // non-Windows invocation is a no-op; on Windows it spawns — never touched here
    const noop = await revokeWriteAces([], 'S-1-4-1-2')
    assert.equal(noop.ok, true)

    // PowerShell host resolution: a host must resolve on win32, none elsewhere
    const host = resolvePowerShell()
    if (process.platform === 'win32') {
      assert.ok(host && host.exe, 'a PowerShell host resolves on win32')
      assert.equal(typeof host.pin51, 'boolean')
    } else {
      assert.equal(host, null)
    }
  }

  // ── grants manifest v2（v1 迁移 / 记账字段 / 往返） ───────────────────────
  {
    const manifestBase = mkdtempSync(join(tmpdir(), 'dsh-grants-man-'))
    try {
      const file = manifestPath(manifestBase)
      // missing file → empty v2; corrupt file → empty v2, never throws
      assert.deepEqual(loadManifest(file), { version: MANIFEST_VERSION, workspaces: {} })
      writeFileSync(file, '{oops', 'utf8')
      assert.deepEqual(loadManifest(file), { version: MANIFEST_VERSION, workspaces: {} })

      // v1 → v2 migration: bare string lists wrap as granted records and ask
      // for a write-back
      writeFileSync(file, JSON.stringify({ workspaces: { 'W:\\work': ['D:\\Shared\\Tools', 'D:\\Data\\logs'] } }), 'utf8')
      const migrated = loadManifest(file)
      assert.equal(migrated.version, MANIFEST_VERSION)
      assert.equal(migrated.needsWriteBack, true)
      const migratedRecord = migrated.workspaces['W:\\work']
      assert.deepEqual(migratedRecord.roots.map((entry) => entry.path), ['D:\\Shared\\Tools', 'D:\\Data\\logs'])
      assert.ok(
        migratedRecord.roots.every((entry) => entry.status === 'granted' && entry.excluded === false && Array.isArray(entry.fromPatterns)),
        'v1 roots wrap as granted, unexcluded records with a fromPatterns list',
      )
      assert.deepEqual(migratedRecord.pendingRevoke, [])
      assert.deepEqual(migratedRecord.history, [])
      saveManifest(file, migrated)
      assert.equal(loadManifest(file).needsWriteBack, undefined) // written back in v2

      // round-trip: a full v2 record (roots + pendingRevoke + history) survives
      const manifest = { version: MANIFEST_VERSION, workspaces: {} }
      const record = workspaceRecord(manifest, 'W:\\work')
      record.sid = 'S-1-4-1-2'
      const entry = ensureRootEntry(record, 'D:\\Shared\\Tools')
      entry.grantedAt = '2026-10-04T00:00:00.000Z'
      entry.fromPatterns = ['D:\\Shared\\**']
      enterPendingRevoke(record, { path: 'D:\\Gone', origin: 'excluded', error: 'boom' })
      pushHistory(record, { path: 'D:\\Old', origin: 'config-removed' })
      saveManifest(file, manifest)
      const loaded = loadManifest(file)
      assert.equal(MANIFEST_FILE_NAME, 'sandbox-allowlist-grants.json')
      assert.equal(loaded.workspaces['W:\\work'].sid, 'S-1-4-1-2')
      assert.equal(
        rootEntryAt(loaded.workspaces['W:\\work'], 'd:\\shared\\tools').grantedAt,
        '2026-10-04T00:00:00.000Z',
        'root lookup is separator/case-insensitive',
      )
      assert.equal(loaded.workspaces['W:\\work'].pendingRevoke[0].origin, 'excluded')
      assert.equal(loaded.workspaces['W:\\work'].history[0].path, 'D:\\Old')

      // accounting: only granted && !excluded entries count as carrying the ACE
      const book = emptyWorkspaceRecord()
      ensureRootEntry(book, 'D:\\A') // default status: granted
      ensureRootEntry(book, 'D:\\B').status = 'failed'
      const excludedEntry = ensureRootEntry(book, 'D:\\C')
      excludedEntry.status = 'granted'
      excludedEntry.excluded = true
      assert.deepEqual(activeEntries(book).map((active) => active.path), ['D:\\A'])
      assert.deepEqual(emptyRootEntry('D:\\X'), {
        path: 'D:\\X', status: 'granted', grantedAt: null, fromPatterns: [], triggeredBy: '',
        excluded: false, error: null, errorAt: null, attempts: 0,
      })
    } finally {
      rmSync(manifestBase, { recursive: true, force: true })
    }
  }

  // ── granted × wanted diff（排除感知，父先序） ─────────────────────────────
  {
    const record = emptyWorkspaceRecord()
    ensureRootEntry(record, 'D:\\x').status = 'granted'
    ensureRootEntry(record, 'D:\\x\\b').status = 'granted'
    const excludedRoot = ensureRootEntry(record, 'D:\\ex') // excluded: revoked however much patterns cover it
    excludedRoot.status = 'granted'
    excludedRoot.excluded = true
    ensureRootEntry(record, 'D:\\fail').status = 'failed' // not in the skip-set → retried

    const plain = diffGrantedV2(record, ['D:\\x', 'D:\\x\\b', 'D:\\new', 'D:\\ex', 'D:\\fail'])
    assert.deepEqual(plain.toAdd.sort(), ['D:\\fail', 'D:\\new'], 'excluded never re-adds; failed retries')
    assert.deepEqual(plain.toRemove, ['D:\\ex'], 'only the excluded still-granted root is revoked here')

    // parents are reclaimed before children (a child must never re-inherit
    // from a batch root that is being reclaimed in the same run)
    const nested = emptyWorkspaceRecord()
    ensureRootEntry(nested, 'D:\\x').status = 'granted'
    ensureRootEntry(nested, 'D:\\x\\b').status = 'granted'
    assert.deepEqual(diffGrantedV2(nested, []).toRemove, ['D:\\x', 'D:\\x\\b'])

    // history-excluded membership: a completed exclusion still blocks re-adding
    const revoked = emptyWorkspaceRecord()
    pushHistory(revoked, { path: 'D:\\gone', origin: 'excluded' })
    assert.deepEqual(diffGrantedV2(revoked, ['D:\\gone']).toAdd, [])
    assert.equal(isExcludedPath(revoked, 'D:\\GONE'), true)

    // duplicate wanted roots collapse; identical sets → no work
    assert.deepEqual(diffGrantedV2(emptyWorkspaceRecord(), ['a', 'a']).toAdd, ['a'])
    const same = diffGrantedV2(emptyWorkspaceRecord(), [])
    assert.deepEqual(same.toAdd, [])
    assert.deepEqual(same.toRemove, [])
  }

  // ── history FIFO 封顶 + pendingRevoke 单条约束 ────────────────────────────
  {
    const record = emptyWorkspaceRecord()
    for (let i = 0; i < HISTORY_LIMIT + 5; i += 1) {
      pushHistory(record, { path: `D:\\h${i}`, origin: 'config-removed', revokedAt: `t${i}` })
    }
    assert.equal(record.history.length, HISTORY_LIMIT)
    assert.equal(record.history[0].path, 'D:\\h5', 'oldest dropped first, order kept')
    assert.equal(record.history.at(-1).path, `D:\\h${HISTORY_LIMIT + 4}`)

    const book = emptyWorkspaceRecord()
    enterPendingRevoke(book, { path: 'D:\\a', origin: 'config-removed', error: 'e1' })
    enterPendingRevoke(book, { path: 'D:\\a', origin: 'excluded', error: 'e2' })
    assert.equal(book.pendingRevoke.length, 1, 'one pendingRevoke entry per path')
    assert.equal(book.pendingRevoke[0].origin, 'excluded')
    assert.equal(dropPendingRevoke(book, 'd:\\A'), true)
    assert.equal(book.pendingRevoke.length, 0)
  }

  // ── fromPatterns 审计镜像 + 入史/剔除原语 ─────────────────────────────────
  {
    const record = emptyWorkspaceRecord()
    ensureRootEntry(record, 'D:\\Shared\\Tools')
    enterPendingRevoke(record, { path: 'D:\\Shared\\Old', origin: 'config-removed' })
    refreshFromPatterns(record, [
      { pattern: 'D:\\Shared\\**', roots: ['D:\\Shared', 'D:\\Shared\\Tools'] },
      { pattern: 'D:\\Other\\*', roots: [] },
    ])
    assert.deepEqual(rootEntryAt(record, 'D:\\Shared\\Tools').fromPatterns, ['D:\\Shared\\**'])
    assert.deepEqual(record.pendingRevoke[0].fromPatterns, [], 'only actual coverage counts')

    assert.equal(moveRootToHistory(record, 'D:\\Shared\\Tools', 'excluded', 't0'), true)
    assert.equal(rootEntryAt(record, 'D:\\Shared\\Tools'), undefined)
    assert.deepEqual(record.history[0], { path: 'D:\\Shared\\Tools', revokedAt: 't0', origin: 'excluded', fromPatterns: ['D:\\Shared\\**'] })
    assert.equal(removeRootEntry(record, 'D:\\missing'), false)
  }

  // ── revoke dir collection (parents first, symlinks never followed) ────────
  {
    const treeBase = mkdtempSync(join(tmpdir(), 'dsh-revoke-tree-'))
    try {
      const root = join(treeBase, 'root')
      mkdirSync(join(root, 'a', 'deep'), { recursive: true })
      writeFileSync(join(root, 'a', 'file.txt'), 'x')
      const { dirs, missing } = collectRevokeDirs([root, join(treeBase, 'gone')])
      assert.deepEqual(missing, [join(treeBase, 'gone')])
      assert.deepEqual(dirs, [root, join(root, 'a'), join(root, 'a', 'deep')])
      assert.ok(!dirs.some((dir) => dir.endsWith('file.txt')), 'files are never collected')
    } finally {
      rmSync(treeBase, { recursive: true, force: true })
    }
  }

  // ── SID 工具（路径重算 / SDDL 形状提取，ki-2 scan 的识别基元） ─────────────
  {
    const dirBase = mkdtempSync(join(tmpdir(), 'dsh-scan-sid-'))
    try {
      const dir = join(dirBase, 'ws')
      mkdirSync(dir, { recursive: true })
      // 路径重算与官方派生一致（sha256 of canonical path），拼写大小写收敛
      const digest = createHash('sha256').update(realpathSync.native(dir), 'utf8').digest()
      const expected = `S-1-4-${digest.readUInt32LE(0) % (2 ** 30 - 1) + 1}-${digest.readUInt32LE(4) % (2 ** 30 - 1) + 1}`
      assert.equal(writeSidForDirectory(dir), expected)
      const flipped = dir.replace(/[a-z]/, (ch) => ch.toUpperCase())
      assert.equal(writeSidForDirectory(flipped), expected, 'canonicalization folds case/alias spellings')
      assert.notEqual(writeSidForDirectory(join(dirBase, 'other')), expected, 'another workspace derives another SID')
      // 目录不存在也能重算（工作区已删除的残留识别场景）
      assert.equal(writeSidForDirectory(join(dirBase, 'gone')), writeSidForDirectory(join(dirBase, 'gone')))
    } finally {
      rmSync(dirBase, { recursive: true, force: true })
    }

    const sddl = 'D:P(A;OICI;W;;;S-1-4-123-456)(A;ID;W;;;S-1-4-987-654)(A;OICI;W;;;S-1-4-111-222-1)(A;;FA;;;S-1-5-18)'
    assert.deepEqual(parseDaclHits(sddl), [
      { sid: 'S-1-4-123-456', inherited: false },
      { sid: 'S-1-4-987-654', inherited: true },
    ], 'workspace shape hits: explicit + inherited copy; temp SID (-1 third subauthority) and S-1-5-18 excluded')
    assert.deepEqual(parseDaclHits(sddl, 'S-1-4-987-654'), [{ sid: 'S-1-4-987-654', inherited: true }], 'exact-sid filter')
    assert.deepEqual(parseDaclHits('D:P(A;OICI;W;;;S-1-4-123-456)(A;ID;W;;;S-1-4-123-456)'), [
      { sid: 'S-1-4-123-456', inherited: false },
      { sid: 'S-1-4-123-456', inherited: true },
    ], 'same sid explicit + inherited copy stay distinct entries')
    assert.deepEqual(parseDaclHits('O:SYG:SYD:PAI(A;;FA;;;BA)'), [], 'no allow ACE → no hits')
  }

  // ── filesystem expansion ───────────────────────────────────────────────────
// Windows 上 TEMP 可能是 8.3 短路径（如 CI runner 的 RUNNER~1），而
// expandTrustedRoots 返回 realpath 规范化路径，夹具必须用同一形态做相等断言
const base = realpathSync.native(mkdtempSync(join(tmpdir(), 'dsh-allowlist-test-')))
try {
  const shared = join(base, 'Shared')
  const sharedA = join(shared, 'a')
  const sharedB = join(shared, 'b')
  const deep = join(sharedB, 'c')
  for (const dir of [shared, sharedA, sharedB, deep]) mkdirSync(dir, { recursive: true })
  writeFileSync(join(sharedA, 'file.txt'), 'x')

  // literal path → the directory itself
  assert.ok(new Set(expandTrustedRoots(shared)).has(shared))

  // trailing `**` → the root itself plus every existing descendant
  const tree = new Set(expandTrustedRoots(join(shared, '**')))
  assert.ok(tree.has(shared), '** includes the anchor root')
  assert.ok(tree.has(sharedA) && tree.has(sharedB) && tree.has(deep), '** includes descendants')

  // single `*` → immediate children only, never the parent
  const children = new Set(expandTrustedRoots(join(shared, '*')))
  assert.ok(children.has(sharedA) && children.has(sharedB), '* includes immediate children')
  assert.ok(!children.has(deep), '* excludes grandchildren')
  assert.ok(!children.has(shared), '* excludes the parent')

  // missing literal → empty, never an error
  assert.deepEqual(expandTrustedRoots(join(base, 'Nope')), [])

  // missing prefix with meta → empty WITHOUT walking the drive (the prefix
  // does not exist, so no path can match)
  assert.deepEqual(expandTrustedRoots(join(base, 'NoSuch', '*')), [])
  assert.deepEqual(expandTrustedRoots(join(base, 'NoSuch', '**')), [])

  // malformed / unsafe patterns → throw with an actionable message
  assert.throws(() => expandTrustedRoots('relative/path'), /must be absolute/)
  assert.throws(() => expandTrustedRoots('D:\\**\\cache'), /anchored too broadly/)

  // ── noRead read-restriction rules ───────────────────────────────────────
  assert.deepEqual(NO_READ_ACTIONS, ['deny', 'ask'], 'no allow action by design')
  assert.deepEqual(NO_READ_TOOLS, ['read', 'read_image', 'edit'])
  assert.ok(validateNoReadRule(null) !== null)
  assert.ok(validateNoReadRule({ pattern: '', action: 'deny' }) !== null, 'empty pattern rejected')
  assert.ok(validateNoReadRule({ pattern: '*.pem', action: 'allow' }) !== null, 'allow action is rejected on purpose')
  assert.ok(validateNoReadRule({ pattern: '*.pem', action: 'bogus' }) !== null)
  assert.equal(validateNoReadRule({ pattern: '*.pem', action: 'deny' }), null)
  assert.equal(validateNoReadRule({ pattern: '.env' }), null, 'action defaults to deny')

  const rules = compileNoReadRules([
    { pattern: '*.pem', action: 'deny' },
    { pattern: '.env*', action: 'deny' },
    { pattern: 'id_rsa', action: 'deny' },
    { pattern: '**/vault/**', action: 'deny' }, // contains a separator ⇒ full-path rule
    { pattern: '*.crt', action: 'ask' },
  ])
  assert.equal(rules.length, 5)
  const hit = (target) => resolveNoRead(rules, target)

  // basename rules match the file name at any depth
  assert.equal(hit('D:\\a\\b.pem').action, 'deny', 'basename rule hits nested files')
  assert.equal(hit('secret.pem').pattern, '*.pem')
  assert.equal(hit('nested/deep/archive.pem').action, 'deny')
  assert.equal(hit('.env').pattern, '.env*', '".env*" also matches ".env" itself (zero-length tail)')
  assert.equal(hit('D:\\x\\.env.local').pattern, '.env*')
  assert.equal(hit('env.local'), null, 'not a dotfile prefix match')
  assert.equal(hit('D:\\users\\me\\.ssh\\id_rsa.pub'), null, 'exact-name rule does not match id_rsa.pub')
  assert.equal(hit('config/id_rsa').pattern, 'id_rsa', 'exact-name rule matches at any depth')
  assert.equal(hit('config/my_rsa'), null, 'only the exact name matches')

  // full-path rules match against the whole path (both separators accepted)
  assert.equal(hit('D:/x/vault/a.txt').pattern, '**/vault/**')
  assert.equal(hit('D:/x/vault/deep/a.txt').action, 'deny')
  assert.equal(hit('D:/x/vaulty/a.txt'), null, 'segment boundary respected')
  assert.equal(hit('vault/a.txt'), null, 'relative path without a leading separator misses the anchored pattern')

  // 回归（M2）：目录级规则对分隔符变体不漏判——模型可用 D:/dir 代替 D:\dir
  const vaultRules = compileNoReadRules([{ pattern: 'D:\\Vault', action: 'deny' }])
  assert.equal(resolveNoRead(vaultRules, 'D:/Vault/secret.txt')?.action, 'deny', 'forward-slash target still matches a backslash dir rule')
  assert.equal(resolveNoRead(vaultRules, 'D:\\Vault\\secret.txt')?.action, 'deny', 'the canonical spelling still matches')
  assert.equal(resolveNoRead(vaultRules, 'D:/Vault2/secret.txt'), null, 'segment boundary respected across separators')
  // 尾部斜杠：规则侧与目标侧的尾分隔符都归一，行为有断言兜底
  const slashed = compileNoReadRules([{ pattern: 'D:/bank/', action: 'deny' }])
  assert.equal(resolveNoRead(slashed, 'D:/bank/x')?.action, 'deny', 'trailing-slash rule spelling normalizes')
  assert.equal(resolveNoRead(vaultRules, 'D:\\Vault\\')?.action, 'deny', 'trailing-slash target still hits the dir rule')

  // case sensitivity follows the platform convention (win insensitive)
  if (process.platform === 'win32') {
    assert.equal(hit('D:\\X\\SECRET.PEM').action, 'deny', 'Windows matching is case-insensitive')
  } else {
    assert.equal(hit('secret.PEM'), null, 'POSIX matching is case-sensitive')
  }

  // deny outranks ask when several rules match one target
  const mixed = compileNoReadRules([
    { pattern: '*.pem', action: 'ask' },
    { pattern: 'secret*', action: 'deny' },
  ])
  assert.deepEqual(resolveNoRead(mixed, 'secret.pem'), { pattern: 'secret*', action: 'deny' }, 'deny beats ask')
  assert.equal(resolveNoRead(mixed, 'other.pem').action, 'ask', 'ask returned when no deny matches')

  // malformed entries are skipped defensively
  assert.equal(compileNoReadRules([{ pattern: '*.pem', action: 'allow' }, { pattern: 'x.txt' }]).length, 1)

  // directory-level rules: an absolute literal dir OR an absolute dir ending
  // in a double-star subtree deny the anchor itself AND everything beneath it;
  // a literal absolute FILE path denies exactly that path (no descendants).
  const win32 = process.platform === 'win32'
  const dirRules = compileNoReadRules([
    { pattern: win32 ? 'D:/vault/**' : '/vault/**', action: 'deny' },     // subtree form
    { pattern: win32 ? 'D:/bank' : '/bank', action: 'deny' },             // literal dir → subtree
    { pattern: win32 ? 'D:/etc-app.conf' : '/etc-app.conf', action: 'deny' }, // literal file (top level, no rule overlap)
  ])
  assert.equal(dirRules.length, 3)
  const dhit = (target) => resolveNoRead(dirRules, target)
  const p = (win) => win ? 'D:/' : '/'
  assert.equal(dhit(`${p(win32)}vault`).action, 'deny', 'subtree rule denies the anchor itself (listing)')
  assert.equal(dhit(`${p(win32)}vault/a/b.txt`).action, 'deny', 'subtree rule denies descendants')
  assert.equal(dhit(`${p(win32)}vault/key.pem`).action, 'deny', 'file under the denied vault is denied by the subtree rule')
  assert.equal(dhit(`${p(win32)}vaultx/a.txt`), null, 'dir segment boundary respected')
  assert.equal(dhit(`${p(win32)}bank`).action, 'deny', 'literal dir denies itself')
  assert.equal(dhit(`${p(win32)}bank/deep/notes.txt`).action, 'deny', 'literal dir denies descendants')
  assert.equal(dhit(`${p(win32)}bank2/x`), null)
  assert.equal(dhit(`${p(win32)}etc-app.conf`).action, 'deny', 'literal file path denies the exact path')
  assert.equal(dhit(`${p(win32)}etc-app.conf.bak`), null, 'literal file path is exact (no prefix leak)')
  if (win32) {
    assert.equal(dhit('D:/VAULT/UP.TXT').action, 'deny', 'Windows dir matching is case-insensitive')
  }

  // breadth guards refuse whole-drive/whole-fs and every-file patterns
  assert.equal(noReadRuleIssues([{ pattern: 'D:\\', action: 'deny' }]).length, 1, 'drive-root dir rule refused')
  assert.equal(noReadRuleIssues([{ pattern: '/', action: 'deny' }]).length, 1, 'fs-root dir rule refused')
  for (const wildcard of ['*', '**', '?']) {
    assert.equal(noReadRuleIssues([{ pattern: wildcard }]).length, 1, `pure wildcard "${wildcard}" refused`)
  }
  assert.equal(compileNoReadRules([{ pattern: 'D:\\', action: 'deny' }, { pattern: '*.pem' }]).length, 1, 'broad rule skipped, concrete rule kept')
  assert.equal(compileNoReadRules([{ pattern: '*', action: 'deny' }]).length, 0)

  // ── plugin classes ───────────────────────────────────────────────────────
  assert.ok(AllowlistPolicyService.prototype instanceof SandboxPolicyService)
  assert.ok(AllowlistFileSystem.prototype instanceof SandboxedFileSystem)
  assert.ok(AllowlistSandboxProvider.prototype instanceof LocalSandboxProvider)
  // The default export is what the loader mounts. On win32 it must stay inert
  // (no LocalSandboxProvider inheritance → no "sandbox" provide) so a
  // user-level patch override that force-enables the provider row cannot
  // collide with the stock provider and fail the boot.
  if (process.platform === 'win32') {
    assert.ok(!(providerDefault.prototype instanceof LocalSandboxProvider), 'default export stays inert on win32')
  } else {
    assert.equal(providerDefault, AllowlistSandboxProvider)
  }

  // ── settings form projection (host `volatileForm` drift guard) ───────────
  // The host projects ONLY `.volatile()` fields into the served settings form
  // and skips entries whose projection is empty — an unmarked rule field
  // would leave configForms.get() with no served namespace and the settings
  // page stuck read-only ("宿主没有提供本插件的设置表单").
  {
    const dict = AllowlistPolicyService.Config.dict ?? {}
    const volatileKeys = Object.keys(dict).filter((key) => dict[key]?.meta?.volatile === true).sort()
    assert.deepEqual(volatileKeys, ['allowedDirs', 'commands', 'noRead'], 'exactly the three rule fields are live-editable')
    assert.ok(dict.mode?.meta?.volatile !== true && dict.workspaceRoot?.meta?.volatile !== true, 'deployment fields stay non-volatile')
  }

  // ── row display metadata (plugin-manager detail pages) ───────────────────
  // The plugin manager resolves each bundle row's title/description from
  // `<row module specifier>/locale/*.json` via the package exports map. The
  // exports keys must exist, the locale directories may hold language-named
  // JSON files only (app boot throws on any other filename), and the provider
  // row must state its platform limitation.
  {
    const pkg = JSON.parse(readFileSync(join(import.meta.dirname, '..', 'package.json'), 'utf8'))
    const languageId = /^[A-Za-z]{2,8}(?:-[A-Za-z0-9]{1,8})*$/u
    for (const row of ['fs', 'provider']) {
      const prefix = `./lib/${row}.mjs/locale/`
      const localeDir = join(import.meta.dirname, '..', 'lib', 'meta', row, 'locale')
      const files = readdirSync(localeDir)
      assert.ok(files.every((f) => f.endsWith('.json') && languageId.test(f.slice(0, -5))), `${row}: locale dir holds language-named JSON only`)
      for (const file of files) {
        const exportsKey = prefix + file
        const target = pkg.exports[exportsKey]
        assert.ok(target, `${row}: exports maps ${exportsKey}`)
        const parsed = JSON.parse(readFileSync(join(import.meta.dirname, '..', target.slice(2)), 'utf8'))
        assert.ok(typeof parsed.meta?.description === 'string' && parsed.meta.description.trim() !== '', `${row}/${file}: meta.description is a non-empty string`)
        assert.equal(parsed.meta.title, undefined, `${row}/${file}: no title override (module path stays the row title)`)
      }
    }
    const providerEn = JSON.parse(readFileSync(join(import.meta.dirname, '..', 'lib', 'meta', 'provider', 'locale', 'en.json'), 'utf8')).meta.description
    assert.ok(providerEn.includes('bwrap') && providerEn.includes('Windows'), 'provider description states its platform limitation')
  }

  // Config schema: parses a full config and applies defaults
  const result = AllowlistPolicyService.Config['~standard'].validate({
    mode: 'workspace-write',
    workspaceRoot: base,
    allowedDirs: [join(shared, '**')],
    commands: { default: 'ask', rules: [{ pattern: 'git *', action: 'allow' }] },
    noRead: [{ pattern: '*.pem' }, { pattern: '**/.env', action: 'ask' }],
  })
  assert.ok('value' in result, 'config validates: ' + JSON.stringify(result.issues))
  const parsed = result.value
  // Volatile fields validate to live references (cosmokit Volatile<T>); read
  // through them exactly like the service does at runtime.
  const readField = (value) => (value !== null && typeof value === 'object' && !Array.isArray(value) && typeof value.get === 'function' ? value.get() : value)
  assert.equal(parsed.mode, 'workspace-write')
  assert.deepEqual(readField(parsed.allowedDirs), [join(shared, '**')])
  const commands = readField(parsed.commands)
  const noRead = readField(parsed.noRead)
  assert.equal(commands.rules.length, 1, 'commands config is parsed')
  assert.equal(commands.default, 'ask')
  assert.equal(parsed.strict, false, 'defaults are applied')
  assert.equal(noRead.length, 2, 'noRead config is parsed')
  assert.equal(noRead[0].action, 'deny', 'noRead rule action defaults to deny')
  assert.equal(noRead[1].action, 'ask')

  // Config schema: rejects junk
  const bad = AllowlistPolicyService.Config['~standard'].validate({ mode: 'bogus' })
  assert.ok('issues' in bad, 'bogus mode is rejected')
  const noReadBad = AllowlistPolicyService.Config['~standard'].validate({
    mode: 'workspace-write',
    workspaceRoot: base,
    noRead: [{ pattern: '*.pem', action: 'allow' }],
  })
  assert.ok('issues' in noReadBad, 'noRead "allow" action is rejected by the config schema')
  const noReadBad2 = AllowlistPolicyService.Config['~standard'].validate({
    mode: 'workspace-write',
    workspaceRoot: base,
    noRead: [{ action: 'deny' }],
  })
  assert.ok('issues' in noReadBad2, 'noRead rule without a pattern is rejected')

  // Settings form source: dsh 0.2.0 keys the form by the Loader entry id and
  // projects the schema from this row's `static Config` — never from a
  // registration API.
  assert.equal(SETTINGS_ENTRY_ID, 'sandbox-allowlist-policy')
  const configWire = JSON.stringify(AllowlistPolicyService.Config.toJSON())
  assert.ok(configWire.includes('安全警示'), 'the form schema carries the warning copy on the wire')
  assert.ok(configWire.includes('noRead'), 'the form schema carries the noRead section on the wire')
  assert.ok(configWire.includes('命令放行规则'), 'the form schema carries the command-rule copy on the wire')

  // Standalone rule-section schema: parses and carries the same warning copy
  const settingsResult = AllowlistSettingsSchema['~standard'].validate({
    allowedDirs: ['D:\\Shared\\**'],
    commands: { default: 'delegate', rules: [{ pattern: 'rm -rf *', action: 'deny' }] },
    noRead: [{ pattern: '*.pem', action: 'deny' }],
  })
  assert.ok('value' in settingsResult, 'settings schema validates')
  assert.deepEqual(settingsResult.value.allowedDirs, ['D:\\Shared\\**'])
  assert.equal(settingsResult.value.commands.rules.length, 1, 'commands section validates')
  assert.equal(settingsResult.value.noRead.length, 1, 'noRead section validates')
  assert.ok('issues' in AllowlistSettingsSchema['~standard'].validate({
    noRead: [{ pattern: '*.pem', action: 'allow' }],
  }), 'settings schema rejects the "allow" action too')
  // The settings page renders schema.toJSON() — the warning must ride the wire
  const wire = JSON.stringify(AllowlistSettingsSchema.toJSON())
  assert.ok(wire.includes('安全警示'), 'settings schema carries the warning copy on the wire')
  assert.ok(wire.includes('noRead'), 'settings schema carries the noRead section on the wire')

  // ── pattern rules over per-statement descriptors ─────────────────────────
  {
    // The statement's program token is normalized before pattern matching:
    // quotes, paths and Windows launcher suffixes disappear, so `git *` also
    // matches a quoted full path to git.exe.
    const pathRules = [{ pattern: 'git *', action: 'allow' }]
    const resolvePath = compileCommandRules(pathRules)
    assert.equal(resolvePath('bash', describeStatement('git status --porcelain')), 'allow')
    assert.equal(resolvePath('bash', describeStatement('"C:\\Program Files\\Git\\git.exe" status')), 'allow', 'a quoted program path reduces to the program name')
    assert.equal(resolvePath('bash', describeStatement('git')), null, 'the bare program does not match the `git *` pattern (needs the space)')
    assert.equal(resolvePath('pwsh', describeStatement('& git status')), 'allow', 'the pwsh call operator is skipped in the normalized text')

    const narrowRules = [
      { pattern: 'git status*', action: 'allow' },
      { pattern: 'git push*', action: 'ask' },
    ]
    const resolveNarrow = compileCommandRules(narrowRules)
    assert.equal(resolveNarrow('bash', describeStatement('git status --porcelain')), 'allow')
    assert.equal(resolveNarrow('bash', describeStatement('git push origin main')), 'ask', 'last match wins within the same statement')
    assert.equal(resolveNarrow('bash', describeStatement('gitdb status')), null, 'patterns anchor at the start, so gitdb never matches git')
    const toolRules = [{ tool: 'pwsh', pattern: 'Get-Content *', action: 'ask' }]
    const resolveTool = compileCommandRules(toolRules)
    assert.equal(resolveTool('pwsh', describeStatement('Get-Content ./id.pem')), 'ask')
    assert.equal(resolveTool('bash', describeStatement('Get-Content ./id.pem')), null, 'a tool-scoped rule does not leak to the other shell')

    // 回归（H2）：program 段两侧折叠、参数段大小写敏感——旗标语义不可被大小写折叠抹掉
    const caseRules = compileCommandRules([{ pattern: 'git branch -d *', action: 'allow' }])
    assert.equal(caseRules('bash', 'git branch -d feature-x'), 'allow', 'the spelled form matches')
    assert.equal(caseRules('bash', 'git branch -D feature-x'), null, 'flag case is semantic: -d must not match -D')
    const pwshCase = compileCommandRules([{ pattern: 'Get-Content *', action: 'ask' }])
    assert.equal(pwshCase('pwsh', 'get-content ./f.txt'), 'ask', 'the program token folds on both sides')

    assert.ok(validateCommandRule({ action: 'allow' }) !== null, 'a rule without a pattern is refused')
    assert.ok(validateCommandRule({ pattern: 'git *', action: 'grant' }) !== null, 'unknown actions are refused')
  }

  // ── capability classification ─────────────────────────────────────────────
  {
    const kind = (statement, options) => classifyStatement(describeStatement(statement), options).kind
    assert.equal(kind('git status'), 'read')
    assert.equal(kind('git push origin main'), 'external')
    assert.equal(kind('git branch -D feature'), 'destructive')
    assert.equal(kind('git commit -m x'), 'local-write')
    assert.equal(kind('git log -5'), 'read')
    assert.equal(kind('cat ./notes.md'), 'read')
    assert.equal(kind('sed s/a/b/ f'), 'opaque', 'sed scripts can execute (e) and write (w/r), so sed is opaque')
    assert.equal(kind('yq .a f.yml'), 'read', 'yq reads')
    assert.equal(kind('yq -i .a f.yml'), 'local-write', 'yq -i writes in place')
    assert.equal(kind('find . -name x'), 'read')
    assert.equal(kind('find . -exec rm {} ;'), 'local-write', 'find -exec is not a read')
    assert.equal(kind('python -c "x"'), 'opaque')
    assert.equal(kind('python --version'), 'read')
    assert.equal(kind('Get-Content x'), 'read', 'approved Get verb')
    assert.equal(kind('Set-Content x y'), 'local-write')
    assert.equal(kind('Remove-Item -Recurse x'), 'destructive')
    assert.equal(kind('docker ps'), 'read', 'docker ps is a read-only form')
    assert.equal(kind('docker run x'), 'external')
    assert.equal(kind('acme-unknown --flag'), 'unknown')

    // 回归（M4）：git 的破坏性 pathspec 形式——checkout/restore 丢弃工作区改动
    assert.equal(kind('git checkout .'), 'destructive', 'checkout with a pathspec discards changes')
    assert.equal(kind('git checkout -- ./f.txt'), 'destructive', 'checkout -- pathspec is destructive')
    assert.equal(kind('git checkout origin/main -- src'), 'destructive', 'checkout <tree> -- path overwrites the working tree')
    assert.equal(kind('git checkout main'), 'local-write', 'branch switching is not destructive')
    assert.equal(kind('git checkout -b feature'), 'local-write', 'branch creation is not destructive')
    assert.equal(kind('git restore .'), 'destructive', 'git restore discards working-tree changes')
    assert.equal(kind('git restore --staged ./f.txt'), 'local-write', 'restore --staged only unstages')

    // 回归（M5）：git grep -O/<pager> 会把 pager 值当程序跑——读类夹带程序加载
    assert.equal(kind("git grep -O'node -e 1' pat"), 'opaque', 'git grep -O runs the pager value as a program')
    assert.equal(kind('git grep --open-files-in-pager pat'), 'opaque', 'long spelling guarded too')
    assert.equal(kind('git grep pat'), 'read', 'a plain grep stays a read')

    // path scope feeds local-write verdicts
    const inScope = (token) => !/^[A-Za-z]:[\\/]/.test(token)
    assert.deepEqual(classifyStatement(describeStatement('mkdir ./logs'), { inScope }).outside, [])
    assert.deepEqual(classifyStatement(describeStatement('mkdir D:/Elsewhere/logs'), { inScope }).outside, ['D:/Elsewhere/logs'])

    // A "read" that names an out-of-scope path reports it, so the escalation
    // gate can refuse it even though the program itself only reads.
    const readOutside = classifyStatement(describeStatement('cat D:/Elsewhere/x'), { inScope })
    assert.equal(readOutside.kind, 'read')
    assert.deepEqual(readOutside.outside, ['D:/Elsewhere/x'], 'a read reports out-of-scope paths')

    // Single source of truth: a program must live in exactly one table. A
    // duplicate whose tables disagree is how a "read-only" label ends up on
    // something that writes.
    {
      const tables = capabilityTables()
      const direct = {
        read: tables.read,
        'local-write': tables.localWrite,
        destructive: tables.destructive,
        opaque: tables.opaque,
        external: tables.external,
        'repo-exec': tables.repoExec,
      }
      const owner = new Map()
      for (const [kind, programs] of Object.entries(direct)) {
        for (const program of programs) {
          assert.equal(owner.get(program), undefined, `"${program}" appears twice in the direct capability tables`)
          owner.set(program, kind)
        }
      }
      // Dispatchers checked BEFORE the direct tables must own their programs
      // exclusively — if they also appear in a direct table, the two can drift.
      for (const { program } of tables.guarded) {
        assert.equal(owner.get(program), undefined, `guarded program "${program}" is also in the ${owner.get(program)} table`)
      }
      for (const program of tables.packageManagers) {
        assert.equal(owner.get(program), undefined, `package manager "${program}" is also in the ${owner.get(program)} table`)
      }
    }
  }

  // ── structural analysis (substitutions / redirects / heredocs) ────────────
  {
    const nested = analyzeCommand('echo $(echo $(whoami))', 'bash', { inScope: () => true })
    assert.deepEqual(nested.statements.map((statement) => statement.program), ['whoami', 'echo', 'echo'], 'nested substitutions are analyzed innermost-first')
    assert.equal(nested.unresolved.length, 0, 'two levels is inside the default depth budget')

    const backtick = analyzeCommand('echo `whoami`', 'bash', { inScope: () => true })
    assert.deepEqual(backtick.statements.map((statement) => statement.program), ['whoami', 'echo'], 'bash backticks are substitutions')
    const pwshBacktick = analyzeCommand('Write-Output a`;b', 'pwsh', { inScope: () => true })
    assert.equal(pwshBacktick.substitutions.length, 0, 'a pwsh backtick is an escape, never a substitution')

    const depth = analyzeCommand('echo $(echo $(echo $(whoami)))', 'bash', { inScope: () => true, maxDepth: 1 })
    assert.ok(depth.unresolved.some((item) => item.kind === 'depth-exceeded'), 'recursion overflow is unresolved (fail-closed)')

    const outOfScope = analyzeCommand('git status > D:/Elsewhere/out.txt', 'bash', {
      inScope: (token) => !token.startsWith('D:/Elsewhere'),
    })
    assert.equal(outOfScope.redirects[0].inScope, false, 'redirect targets are resolved against the scope')

    const single = analyzeCommand("echo 'no $(substitution) here'", 'bash', { inScope: () => true })
    assert.equal(single.substitutions.length, 0, 'single quotes suppress substitution')

    // 回归（C1）：heredoc 定界符只认字面位置的 << —— 字符串参数里的 '<<EOF'
    // 不得开启伪 heredoc，否则后续真实命令行会被当作 DATA 吞掉、逃过判定。
    const quotedMarker = analyzeCommand("grep '<<EOF' file\nrm -rf ./gone\nEOF\necho done", 'bash', { inScope: () => true })
    assert.ok(quotedMarker.statements.some((statement) => statement.text.includes('rm -rf')), 'a quoted <<EOF is a string argument, not a heredoc opener')
    assert.ok(quotedMarker.statements.some((statement) => statement.text.trim() === 'echo done'), 'lines after the false opener stay visible to analysis')
    const realHeredoc = analyzeCommand('cat > ./out.txt <<EOF\nhello\nEOF\necho done', 'bash', { inScope: () => true })
    assert.equal(realHeredoc.statements.some((statement) => statement.text.includes('hello')), false, 'a real heredoc body is data, never a statement')
    assert.ok(realHeredoc.statements.some((statement) => statement.text.trim() === 'echo done'), 'statements after the heredoc body are analyzed')

    // 回归（C2）：链式重定向的每个目标都要单独过 scope 检查
    const chained = analyzeCommand('echo pwned > ./ok.txt>D:/Elsewhere/evil.txt', 'bash', {
      inScope: (token) => !token.startsWith('D:/Elsewhere'),
    })
    assert.equal(chained.redirects.length, 2, 'chained redirects produce one entry per target')
    assert.equal(chained.redirects[1].inScope, false, 'the second target is checked, not swallowed into the first')

    // 回归（H1）：目标是命令替换的重定向不可解析（fail-closed），绝不判无害
    const dynamicTarget = analyzeCommand('echo pwned > $(cat t.txt)', 'bash', { inScope: () => true })
    assert.ok(dynamicTarget.unresolved.some((item) => item.kind === 'redirect-target'), 'a substitution redirect target is unresolved')

    // 回归（M3）：>&2 等 fd 复制不是分隔符，语句不被 & 拆断
    const fdDup = analyzeCommand('echo hi >&2', 'bash', { inScope: () => true })
    assert.equal(fdDup.statements.length, 1, 'fd duplication keeps the statement whole')
    assert.ok(fdDup.statements[0].text.includes('>&2'), 'and the fd-dup text survives splitting')
  }

  // ── scope predicate (workspace ∪ granted roots) ───────────────────────────
  {
    const inScope = makeScopePredicate(['D:/Repo', 'D:/Shared/Tools'], 'D:/Repo')
    assert.equal(inScope('D:/Repo/src/a.ts'), true)
    assert.equal(inScope('./src/a.ts'), true, 'relative paths resolve against the cwd')
    assert.equal(inScope('D:\\Repo\\src\\a.ts'), true, 'backslashes normalize')
    assert.equal(inScope('D:/Repo2/a.ts'), false, 'a sibling with a shared prefix is NOT inside')
    assert.equal(inScope('D:/Shared/Tools/x'), true, 'granted roots count as inside')
    assert.equal(inScope('D:/Elsewhere/x'), false)
    assert.equal(inScope('../../Elsewhere/x'), false, '.. escapes are resolved before the check')
    assert.equal(inScope('~/.ssh/id_rsa'), false, 'home-relative paths leave the workspace')
    assert.equal(inScope('/etc/passwd'), false, 'a POSIX absolute path has no known mapping')
    // 回归（L1）：无 cwd 时相对路径不可证明在界内（fail-closed）；POSIX 根的
    // 宿主上 POSIX 绝对路径可以正常比较。
    const noCwd = makeScopePredicate(['D:/Repo'], undefined)
    assert.equal(noCwd('./src/a.ts'), false, 'a relative path with no cwd cannot be proven in scope')
    const posixRoots = makeScopePredicate(['/home/me/repo'], '/home/me/repo')
    assert.equal(posixRoots('/home/me/repo/a.ts'), true, 'POSIX absolute tokens compare on a POSIX-rooted host')
    assert.equal(posixRoots('/etc/passwd'), false, 'and still refuse paths outside the roots')
  }

  // ── meta-program expansion (package.json scripts) ─────────────────────────
  {
    const manifest = JSON.stringify({
      scripts: { test: 'vitest run', deploy: 'sh ./deploy.sh', pretest: 'node ./prep.mjs', lint: 'eslint src' },
    })
    assert.equal(scriptNameOf('pnpm', 'test', (name) => name === 'test'), 'test', 'bare subcommand resolving to a script')
    assert.equal(scriptNameOf('pnpm', 'install', () => false), null, 'a bare builtin is not a script when none is defined')
    assert.equal(scriptNameOf('npm', 'run lint', () => true), 'lint', 'explicit run subcommand')
    assert.equal(scriptNameOf('node', 'test', () => true), null, 'only package managers expand')

    const expand = makeScriptExpander({ workspaceRoot: 'D:/Repo', readFile: () => manifest, onWarn: () => {} })
    assert.match(expand('pnpm', 'test'), /node \.\/prep\.mjs/, 'pre-lifecycle hooks are folded in')
    assert.match(expand('pnpm', 'test'), /vitest run/, 'the script body is included')
    assert.equal(expand('pnpm', 'publish'), null, 'not a script')
    const broken = makeScriptExpander({ workspaceRoot: 'D:/Repo', readFile: () => { throw new Error('ENOENT') }, onWarn: () => {} })
    assert.equal(broken('pnpm', 'test'), null, 'an unreadable manifest degrades to null (fail-closed)')
    // 回归（C3）：runner 附加参数由包管理器转发给脚本——并入具名脚本体判定
    assert.match(expand('pnpm', 'test -- --reporter dot'), /vitest run -- --reporter dot/, 'runner arguments are folded into the named script body')
    assert.equal(expand('pnpm', 'run lint -- --fix'), 'eslint src -- --fix', 'args reach the named script, not the hooks')
  }

  // ── decision engine: aggregation and explanations ─────────────────────────
  {
    const context = { roots: ['D:/Repo'], cwd: 'D:/Repo' }
    const sandbox = (source, command, tool = 'bash') => decide({ source, tool, command, phase: 'sandbox', context })
    const denyWins = sandbox({ rules: [{ pattern: 'rm *', action: 'deny' }, { pattern: 'pnpm *', action: 'allow' }], default: 'delegate' }, 'pnpm lint; rm -rf ./x')
    assert.equal(denyWins.verdict, 'deny', 'deny outranks allow across statements')
    const askWins = sandbox({ rules: [{ pattern: 'git push*', action: 'ask' }], default: 'delegate' }, 'git status && git push')
    assert.equal(askWins.verdict, 'ask', 'ask outranks the baseline')
    const baseline = sandbox({ rules: [], default: 'delegate' }, 'git status | cat')
    assert.equal(baseline.verdict, 'allow', 'the baseline allows read-only statements with no rules')
    const noBaseline = sandbox({ rules: [], default: 'delegate', baseline: false }, 'git status | cat')
    assert.equal(noBaseline.verdict, 'delegate', 'baseline=false returns the decision to the rules')
    const delegated = sandbox({ rules: [], default: 'delegate' }, 'acme-tool run')
    assert.equal(delegated.verdict, 'delegate', 'an unknown program delegates')

    // 回归（C3 端到端）：脚本展开带上的 runner 参数若指向界外，升级栅栏必须拦下
    const expandCtx = {
      ...context,
      expandScript: makeScriptExpander({
        workspaceRoot: 'D:/Repo',
        readFile: () => JSON.stringify({ scripts: { save: 'tee' } }),
        onWarn: () => {},
      }),
    }
    const laundered = decide({ source: { rules: [] }, tool: 'bash', command: 'pnpm save -- D:/Elsewhere/evil.txt', phase: 'escalation', context: expandCtx })
    assert.equal(laundered.escalate, false, 'an out-of-scope runner argument blocks the auto-escalation')
    const inScopeArg = decide({ source: { rules: [] }, tool: 'bash', command: 'pnpm save -- D:/Repo/ok.txt', phase: 'escalation', context: expandCtx })
    assert.equal(inScopeArg.escalate, true, 'an in-scope runner argument still auto-escalates')

    const explained = explainDecision(denyWins)
    assert.match(explained, /判定：deny/, 'explainDecision renders the verdict')
    assert.match(explained, /rm -rf \.\/x/, 'and the per-statement breakdown')
  }

  // ── audit / proposals ─────────────────────────────────────────────────────
  {
    const audit = new CommandAudit({ cap: 2, file: join(base, 'decisions.jsonl') })
    audit.record({ phase: 'sandbox', tool: 'bash', command: 'a', verdict: 'allow' })
    audit.record({ phase: 'sandbox', tool: 'bash', command: 'b', verdict: 'ask' })
    audit.record({ phase: 'escalation', tool: 'bash', command: 'c', verdict: 'ask' })
    assert.equal(audit.recent().length, 2, 'the ring is bounded')
    assert.equal(audit.recent()[1].command, 'c', 'the newest entry is last')
    assert.ok(existsSync(join(base, 'decisions.jsonl')), 'the JSONL audit sink is written')

    // The append-only sink rotates instead of growing for the lifetime of the
    // installation (a 2 MiB default, tiny here to keep the test fast).
    const rotating = new CommandAudit({ file: join(base, 'rotate.jsonl'), maxBytes: 200, maxFiles: 2 })
    for (let i = 0; i < 12; i += 1) {
      rotating.record({ phase: 'sandbox', tool: 'bash', command: `cmd-${i}`, verdict: 'allow' })
    }
    assert.ok(existsSync(join(base, 'rotate.jsonl.1')), 'the sink rotated once it passed maxBytes')
    assert.ok(
      statSync(join(base, 'rotate.jsonl')).size <= 200 + 400,
      'the live sink is bounded (a rotation happens once per maxBytes)',
    )
    assert.ok(!existsSync(join(base, 'rotate.jsonl.3')), 'rotated files beyond maxFiles are dropped')

    const proposals = new ProposalStore({ threshold: 2 })
    assert.equal(proposals.note({ tool: 'bash', program: 'cargo', rest: 'fmt', kind: 'opaque', phase: 'escalation' }), null, 'below threshold: no proposal yet')
    const proposed = proposals.note({ tool: 'bash', program: 'cargo', rest: 'fmt', kind: 'opaque', phase: 'escalation' })
    assert.equal(proposed.program, 'cargo', 'the second approval proposes a rule')
    assert.equal(proposed.action, 'allow', 'every proposal is an allow rule (it carries the escalation grant by itself)')
    assert.deepEqual(proposals.proposedRules()[0].pattern, 'cargo fmt*', 'the proposal converts to a pattern rule')
    assert.match(describeProposal(proposed), /cargo fmt\*/, 'the proposal renders readably')
  }

  console.log('dsh-sandbox-allowlist: all checks passed')
} finally {
  rmSync(base, { recursive: true, force: true })
}