/**
 * Self-check for the dsh-sandbox-allowlist package.
 *
 * Run inside the dsh installation context so `@deepseek-ai/*` resolves to the
 * installed packages. On this machine:
 *
 *   node --experimental-loader ./.dsh-test-resolve-hook.mjs test.mjs
 *
 * (the resolve-hook is generated by the dsh tooling; see README "验证").
 * Without the hook the @deepseek-ai imports fail to resolve — the pattern
 * checks can still be run standalone by commenting the plugin imports.
 */

import assert from 'node:assert/strict'
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

import {
  hasMeta,
  patternToRegExp,
  expandTrustedRoots,
} from '../lib/patterns.mjs'
import AllowlistPolicyService, { SETTINGS_NAMESPACE, AllowlistSettingsSchema } from '../lib/policy.mjs'
import AllowlistFileSystem from '../lib/fs.mjs'
import AllowlistSandboxProvider from '../lib/provider.mjs'
import { SandboxPolicyService } from '@deepseek-ai/dsh-sandbox-policy'
import { SandboxedFileSystem } from '@deepseek-ai/dsh-fs-sandbox'
import { LocalSandboxProvider } from '@deepseek-ai/dsh-sandbox-local'

// ── pattern matcher ────────────────────────────────────────────────────────
assert.equal(hasMeta('D:\\Shared\\Tools'), false)
assert.equal(hasMeta('D:\\Data\\logs\\*'), true)
assert.equal(hasMeta('D:\\**\\cache'), true)

const reDoubleStar = patternToRegExp('D:\\Shared\\**')
assert.ok(reDoubleStar.test('D:\\Shared\\a'))
assert.ok(reDoubleStar.test('D:\\Shared\\a\\b\\c'))
assert.ok(!reDoubleStar.test('D:\\SharedOther\\a'))

const reSingleStar = patternToRegExp('D:\\Data\\logs\\*')
assert.ok(reSingleStar.test('D:\\Data\\logs\\x'))
assert.ok(!reSingleStar.test('D:\\Data\\logs\\x\\y'))

// ── filesystem expansion ───────────────────────────────────────────────────
const base = mkdtempSync(join(tmpdir(), 'dsh-allowlist-test-'))
try {
  const shared = join(base, 'Shared')
  const sharedA = join(shared, 'a')
  const sharedB = join(shared, 'b')
  const deep = join(sharedB, 'c')
  for (const dir of [shared, sharedA, sharedB, deep]) mkdirSync(dir, { recursive: true })
  writeFileSync(join(sharedA, 'file.txt'), 'x')

  // literal path → the directory itself
  assert.ok(new Set(expandTrustedRoots(shared)).has(shared))

  // trailing `**` → the root itself plus every existing descendant
  const tree = new Set(expandTrustedRoots(join(shared, '**')))
  assert.ok(tree.has(shared), '** includes the anchor root')
  assert.ok(tree.has(sharedA) && tree.has(sharedB) && tree.has(deep), '** includes descendants')

  // single `*` → immediate children only, never the parent
  const children = new Set(expandTrustedRoots(join(shared, '*')))
  assert.ok(children.has(sharedA) && children.has(sharedB), '* includes immediate children')
  assert.ok(!children.has(deep), '* excludes grandchildren')
  assert.ok(!children.has(shared), '* excludes the parent')

  // missing literal → empty, never an error
  assert.deepEqual(expandTrustedRoots(join(base, 'Nope')), [])

  // missing prefix with meta → empty WITHOUT walking the drive (the prefix
  // does not exist, so no path can match)
  assert.deepEqual(expandTrustedRoots(join(base, 'NoSuch', '*')), [])
  assert.deepEqual(expandTrustedRoots(join(base, 'NoSuch', '**')), [])

  // malformed / unsafe patterns → throw with an actionable message
  assert.throws(() => expandTrustedRoots('relative/path'), /must be absolute/)
  assert.throws(() => expandTrustedRoots('D:\\**\\cache'), /anchored too broadly/)

  // ── plugin classes ───────────────────────────────────────────────────────
  assert.ok(AllowlistPolicyService.prototype instanceof SandboxPolicyService)
  assert.ok(AllowlistFileSystem.prototype instanceof SandboxedFileSystem)
  assert.ok(AllowlistSandboxProvider.prototype instanceof LocalSandboxProvider)

  // Config schema: parses a full config and applies defaults
  const result = AllowlistPolicyService.Config['~standard'].validate({
    mode: 'workspace-write',
    workspaceRoot: base,
    allowedDirs: [join(shared, '**')],
  })
  assert.ok('value' in result, 'config validates: ' + JSON.stringify(result.issues))
  const parsed = result.value
  assert.equal(parsed.mode, 'workspace-write')
  assert.deepEqual(parsed.allowedDirs, [join(shared, '**')])
  assert.equal(parsed.strict, false, 'defaults are applied')

  // Config schema: rejects junk
  const bad = AllowlistPolicyService.Config['~standard'].validate({ mode: 'bogus' })
  assert.ok('issues' in bad, 'bogus mode is rejected')

  // Settings namespace schema: parses and carries the warning copy
  assert.equal(SETTINGS_NAMESPACE, 'sandbox-allowlist')
  const settingsResult = AllowlistSettingsSchema['~standard'].validate({
    allowedDirs: ['D:\\Shared\\**'],
  })
  assert.ok('value' in settingsResult, 'settings schema validates')
  assert.deepEqual(settingsResult.value.allowedDirs, ['D:\\Shared\\**'])
  // The settings page renders schema.toJSON() — the warning must ride the wire
  const wire = JSON.stringify(AllowlistSettingsSchema.toJSON())
  assert.ok(wire.includes('安全警示'), 'settings schema carries the warning copy on the wire')

  console.log('dsh-sandbox-allowlist: all checks passed')
} finally {
  rmSync(base, { recursive: true, force: true })
}
