/**
 * Self-check for the dsh-sandbox-allowlist package.
 *
 * Run inside the dsh installation context so `@deepseek-ai/*` resolves to the
 * installed packages. On this machine:
 *
 *   node --experimental-loader ./.dsh-test-resolve-hook.mjs test.mjs
 *
 * (the resolve-hook is generated by the dsh tooling; see README "验证").
 * Without the hook the @deepseek-ai imports fail to resolve — the pattern
 * checks can still be run standalone by commenting the plugin imports.
 */

import assert from 'node:assert/strict'
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

import {
  hasMeta,
  patternToRegExp,
  expandTrustedRoots,
} from '../lib/patterns.mjs'
import {
  normalizeCommand,
  patternToCommandRegExp,
  compileCommandRules,
  resolveCommandAction,
  validateCommandRule,
} from '../lib/command-rules.mjs'
import {
  decideCommand,
  dispositionForAction,
  denyReason,
} from '../lib/command-gate.mjs'
import {
  stripDaclSddl,
  revokeWriteAces,
  collectRevokeDirs,
  resolvePowerShell,
} from '../lib/acl-revoke.mjs'
import {
  MANIFEST_FILE_NAME,
  manifestPath,
  loadManifest,
  saveManifest,
  workspaceGrants,
  setWorkspaceGrants,
  diffGranted,
} from '../lib/grant-manifest.mjs'
import AllowlistPolicyService, { SETTINGS_NAMESPACE, AllowlistSettingsSchema, CommandRuleSchema, CommandSettingsSchema } from '../lib/policy.mjs'
import AllowlistFileSystem from '../lib/fs.mjs'
import AllowlistSandboxProvider from '../lib/provider.mjs'
import { SandboxPolicyService } from '@deepseek-ai/dsh-sandbox-policy'
import { SandboxedFileSystem } from '@deepseek-ai/dsh-fs-sandbox'
import { LocalSandboxProvider } from '@deepseek-ai/dsh-sandbox-local'

// ── pattern matcher ────────────────────────────────────────────────────────
assert.equal(hasMeta('D:\\Shared\\Tools'), false)
assert.equal(hasMeta('D:\\Data\\logs\\*'), true)
assert.equal(hasMeta('D:\\**\\cache'), true)

const reDoubleStar = patternToRegExp('D:\\Shared\\**')
assert.ok(reDoubleStar.test('D:\\Shared\\a'))
assert.ok(reDoubleStar.test('D:\\Shared\\a\\b\\c'))
assert.ok(!reDoubleStar.test('D:\\SharedOther\\a'))

const reSingleStar = patternToRegExp('D:\\Data\\logs\\*')
assert.ok(reSingleStar.test('D:\\Data\\logs\\x'))
assert.ok(!reSingleStar.test('D:\\Data\\logs\\x\\y'))

// ── command rules ──────────────────────────────────────────────────────────
// normalizing collapses surrounding and inner whitespace; ignores casing on win32
assert.equal(normalizeCommand('  git   status  '), 'git status')
assert.equal(normalizeCommand(''), '')
assert.equal(normalizeCommand(null), '')

// wildcard translation: `*` any run, `?` one char, anchored
const gitAny = patternToCommandRegExp('git *')
assert.ok(gitAny.test('git status --porcelain'))
assert.ok(gitAny.test('git commit -m hi'))
assert.ok(!gitAny.test('git'))
const gitCommit = patternToCommandRegExp('git commit *')
assert.ok(gitCommit.test('git commit -m hi'))
assert.ok(!gitCommit.test('git status'))
assert.ok(patternToCommandRegExp('git statu?').test('git status'))

// last-match-wins with tool-aware rules
const rules = [
  { tool: 'bash', pattern: 'git *', action: 'allow' },
  { tool: 'pwsh', pattern: 'git *', action: 'ask' },
  { pattern: 'rm -rf *', action: 'deny' }, // tool omitted ⇒ all tools
  { tool: 'bash', pattern: 'git push *', action: 'deny' }, // more specific, later
]
const match = compileCommandRules(rules)
assert.equal(match('bash', 'git status'), 'allow')
assert.equal(match('pwsh', 'git status'), 'ask')
assert.equal(match('bash', 'git push origin main'), 'deny') // last match wins
assert.equal(match('bash', 'rm -rf /tmp/x'), 'deny')        // tool-omitted applies to bash
assert.equal(match('pwsh', 'rm -rf /tmp/x'), 'deny')        // and to pwsh
assert.equal(match('bash', 'npm test'), null)               // no match

// resolveCommandAction applies the configured fallback (delegate keeps behavior)
assert.equal(resolveCommandAction(rules, 'bash', 'npm test', 'delegate'), 'delegate')
assert.equal(resolveCommandAction(rules, 'bash', 'npm test', 'ask'), 'ask')
assert.equal(resolveCommandAction([], 'bash', 'npm test', 'delegate'), 'delegate')

// malformed rules are skipped, never thrown
assert.equal(validateCommandRule({ pattern: 'git *', action: 'allow' }), null)
assert.ok(validateCommandRule({ pattern: 'git *', action: 'bogus' }) !== null)
assert.ok(validateCommandRule({ pattern: '' }) !== null)
assert.ok(validateCommandRule({ tool: 'cmd', pattern: 'x', action: 'allow' }) !== null)

// gate decision → PreToolDecision-shaped result, with delegate sentinel
assert.equal(decideCommand({ rules, default: 'delegate' }, 'bash', 'npm test'), 'delegate')
assert.deepEqual(decideCommand({ rules }, 'bash', 'git status'), { kind: 'allow' })
assert.deepEqual(decideCommand({ rules }, 'bash', 'git push origin main'), { kind: 'deny' })
assert.deepEqual(decideCommand({ rules, default: 'ask' }, 'bash', 'npm test'), { kind: 'ask' })
assert.deepEqual(decideCommand({ rules }, 'bash', 'GIT STATUS'), { kind: 'allow' }) // win32 case-insensitive
assert.equal(dispositionForAction('allow').kind, 'allow')
assert.equal(dispositionForAction('deny').kind, 'deny')
assert.equal(dispositionForAction('ask').kind, 'ask')
assert.equal(dispositionForAction('bogus'), 'delegate')
assert.match(denyReason('bash', 'rm -rf /'), /deny rule/)

// command rule / settings schemas validate and reject junk
{
  const ruleResult = CommandRuleSchema['~standard'].validate({ pattern: 'git *', action: 'allow' })
  assert.ok('value' in ruleResult, 'command rule validates: ' + JSON.stringify(ruleResult.issues))
  assert.equal(ruleResult.value.pattern, 'git *')
  const toolResult = CommandRuleSchema['~standard'].validate({ tool: 'bash', pattern: 'git *', action: 'allow' })
  assert.ok('value' in toolResult, 'rule with tool validates')
  const badAction = CommandRuleSchema['~standard'].validate({ pattern: 'git *', action: 'go' })
  assert.ok('issues' in badAction, 'rule rejects an unknown action')
  const badTool = CommandRuleSchema['~standard'].validate({ tool: 'cmd', pattern: 'x', action: 'allow' })
  assert.ok('issues' in badTool, 'rule rejects an unknown tool')

  const cmds = CommandSettingsSchema['~standard'].validate({ default: 'ask', rules: [{ pattern: 'git *', action: 'allow' }] })
  assert.ok('value' in cmds, 'commands settings validates')
  assert.equal(cmds.value.default, 'ask')
  assert.equal(cmds.value.rules.length, 1)
}

// ── ACL reclamation (SDDL strip is pure; spawn helpers stay platform-safe) ──
  {
    // explicit + inherited copies of the workspace SID are dropped in one pass
    const sddl = 'D:AI(A;OICI;0x110156;;;S-1-4-1-2)(A;OICIID;0x110156;;;S-1-4-1-2)(A;ID;FA;;;BA)'
    const out = stripDaclSddl(sddl, 'S-1-4-1-2')
    assert.equal(out.count, 2)
    assert.equal(out.sddl, 'D:AI(A;ID;FA;;;BA)')

    // absent SID → untouched, zero count
    const untouched = stripDaclSddl('D:(A;ID;FA;;;SY)', 'S-1-4-9-9')
    assert.equal(untouched.count, 0)
    assert.equal(untouched.sddl, 'D:(A;ID;FA;;;SY)')

    // every segment naming the SID is removed, others preserved in order
    const multiple = stripDaclSddl('D:(A;OICI;0x110156;;;S-1-4-7-8)(A;ID;0x1301bf;;;AU)(A;OICI;0x110156;;;S-1-4-7-8)', 'S-1-4-7-8')
    assert.equal(multiple.count, 2)
    assert.equal(multiple.sddl, 'D:(A;ID;0x1301bf;;;AU)')

    // an empty/short DACL round-trips unchanged
    assert.equal(stripDaclSddl('D:', 'S-1-4-1-1').sddl, 'D:')

    // non-Windows invocation is a no-op; on Windows it spawns — never touched here
    const noop = revokeWriteAces([], 'S-1-4-1-2')
    assert.equal(noop.ok, true)

    // PowerShell host resolution: a host must resolve on win32, none elsewhere
    const host = resolvePowerShell()
    if (process.platform === 'win32') {
      assert.ok(host && host.exe, 'a PowerShell host resolves on win32')
      assert.equal(typeof host.pin51, 'boolean')
    } else {
      assert.equal(host, null)
    }
  }

  // ── grants manifest ───────────────────────────────────────────────────────
  {
    const manifestBase = mkdtempSync(join(tmpdir(), 'dsh-grants-man-'))
    try {
      // missing file → empty; corrupt file → empty, never throws
      const missing = manifestPath(manifestBase)
      assert.deepEqual(loadManifest(missing), { workspaces: {} })
      writeFileSync(missing, '{oops', 'utf8')
      assert.deepEqual(loadManifest(missing), { workspaces: {} })

      // round-trip: save → load → per-workspace get/set
      const manifest = { workspaces: {} }
      setWorkspaceGrants(manifest, 'W:\\work', ['D:\\Shared\\Tools', 'D:\\Data\\logs'])
      saveManifest(missing, manifest)
      const loaded = loadManifest(missing)
      assert.deepEqual(workspaceGrants(loaded, 'W:\\work'), ['D:\\Shared\\Tools', 'D:\\Data\\logs'])
      assert.deepEqual(workspaceGrants(loaded, 'W:\\other'), [])
      assert.equal(loaded.workspaces['W:\\work'].length, 2)
      assert.equal(MANIFEST_FILE_NAME, 'sandbox-allowlist-grants.json')
    } finally {
      rmSync(manifestBase, { recursive: true, force: true })
    }
  }

  // ── granted × wanted diff ─────────────────────────────────────────────────
  {
    const plain = diffGranted(['a', 'b'], ['b', 'c'])
    assert.deepEqual(plain.toAdd, ['c'])
    assert.deepEqual(plain.toRemove, ['a'])

    // parents are reclaimed before children (a child must never re-inherit
    // from a batch root that is being reclaimed in the same run)
    const nested = diffGranted(['D:\\x\\b', 'D:\\x'], [])
    assert.deepEqual(nested.toRemove, ['D:\\x', 'D:\\x\\b'])

    // duplicate wanted roots collapse
    assert.deepEqual(diffGranted([], ['a', 'a']).toAdd, ['a'])

    // identical sets → no work
    const same = diffGranted(['a', 'b'], ['b', 'a'])
    assert.deepEqual(same.toAdd, [])
    assert.deepEqual(same.toRemove, [])
  }

  // ── revoke dir collection (parents first, symlinks never followed) ────────
  {
    const treeBase = mkdtempSync(join(tmpdir(), 'dsh-revoke-tree-'))
    try {
      const root = join(treeBase, 'root')
      mkdirSync(join(root, 'a', 'deep'), { recursive: true })
      writeFileSync(join(root, 'a', 'file.txt'), 'x')
      const { dirs, missing } = collectRevokeDirs([root, join(treeBase, 'gone')])
      assert.deepEqual(missing, [join(treeBase, 'gone')])
      assert.deepEqual(dirs, [root, join(root, 'a'), join(root, 'a', 'deep')])
      assert.ok(!dirs.some((dir) => dir.endsWith('file.txt')), 'files are never collected')
    } finally {
      rmSync(treeBase, { recursive: true, force: true })
    }
  }

  // ── filesystem expansion ───────────────────────────────────────────────────
const base = mkdtempSync(join(tmpdir(), 'dsh-allowlist-test-'))
try {
  const shared = join(base, 'Shared')
  const sharedA = join(shared, 'a')
  const sharedB = join(shared, 'b')
  const deep = join(sharedB, 'c')
  for (const dir of [shared, sharedA, sharedB, deep]) mkdirSync(dir, { recursive: true })
  writeFileSync(join(sharedA, 'file.txt'), 'x')

  // literal path → the directory itself
  assert.ok(new Set(expandTrustedRoots(shared)).has(shared))

  // trailing `**` → the root itself plus every existing descendant
  const tree = new Set(expandTrustedRoots(join(shared, '**')))
  assert.ok(tree.has(shared), '** includes the anchor root')
  assert.ok(tree.has(sharedA) && tree.has(sharedB) && tree.has(deep), '** includes descendants')

  // single `*` → immediate children only, never the parent
  const children = new Set(expandTrustedRoots(join(shared, '*')))
  assert.ok(children.has(sharedA) && children.has(sharedB), '* includes immediate children')
  assert.ok(!children.has(deep), '* excludes grandchildren')
  assert.ok(!children.has(shared), '* excludes the parent')

  // missing literal → empty, never an error
  assert.deepEqual(expandTrustedRoots(join(base, 'Nope')), [])

  // missing prefix with meta → empty WITHOUT walking the drive (the prefix
  // does not exist, so no path can match)
  assert.deepEqual(expandTrustedRoots(join(base, 'NoSuch', '*')), [])
  assert.deepEqual(expandTrustedRoots(join(base, 'NoSuch', '**')), [])

  // malformed / unsafe patterns → throw with an actionable message
  assert.throws(() => expandTrustedRoots('relative/path'), /must be absolute/)
  assert.throws(() => expandTrustedRoots('D:\\**\\cache'), /anchored too broadly/)

  // ── plugin classes ───────────────────────────────────────────────────────
  assert.ok(AllowlistPolicyService.prototype instanceof SandboxPolicyService)
  assert.ok(AllowlistFileSystem.prototype instanceof SandboxedFileSystem)
  assert.ok(AllowlistSandboxProvider.prototype instanceof LocalSandboxProvider)

  // Config schema: parses a full config and applies defaults
  const result = AllowlistPolicyService.Config['~standard'].validate({
    mode: 'workspace-write',
    workspaceRoot: base,
    allowedDirs: [join(shared, '**')],
    commands: { default: 'ask', rules: [{ pattern: 'git *', action: 'allow' }] },
  })
  assert.ok('value' in result, 'config validates: ' + JSON.stringify(result.issues))
  const parsed = result.value
  assert.equal(parsed.mode, 'workspace-write')
  assert.deepEqual(parsed.allowedDirs, [join(shared, '**')])
  assert.equal(parsed.commands.rules.length, 1, 'commands config is parsed')
  assert.equal(parsed.commands.default, 'ask')
  assert.equal(parsed.strict, false, 'defaults are applied')

  // Config schema: rejects junk
  const bad = AllowlistPolicyService.Config['~standard'].validate({ mode: 'bogus' })
  assert.ok('issues' in bad, 'bogus mode is rejected')

  // Settings namespace schema: parses and carries the warning copy
  assert.equal(SETTINGS_NAMESPACE, 'sandbox-allowlist')
  const settingsResult = AllowlistSettingsSchema['~standard'].validate({
    allowedDirs: ['D:\\Shared\\**'],
    commands: { default: 'delegate', rules: [{ pattern: 'rm -rf *', action: 'deny' }] },
  })
  assert.ok('value' in settingsResult, 'settings schema validates')
  assert.deepEqual(settingsResult.value.allowedDirs, ['D:\\Shared\\**'])
  assert.equal(settingsResult.value.commands.rules.length, 1, 'commands section validates')
  // The settings page renders schema.toJSON() — the warning must ride the wire
  const wire = JSON.stringify(AllowlistSettingsSchema.toJSON())
  assert.ok(wire.includes('安全警示'), 'settings schema carries the warning copy on the wire')

  console.log('dsh-sandbox-allowlist: all checks passed')
} finally {
  rmSync(base, { recursive: true, force: true })
}
